//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt02_actividad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIt02_actividad()
        {
            this.CLIt03_atencion = new HashSet<CLIt03_atencion>();
            this.CLIt04_atencion_dtl = new HashSet<CLIt04_atencion_dtl>();
        }
    
        public long id_actividad { get; set; }
        public string cod_actividad { get; set; }
        public string txt_desc { get; set; }
        public string txt_observacion { get; set; }
        public Nullable<int> nro_orden { get; set; }
        public Nullable<int> id_actividad_prev { get; set; }
        public Nullable<int> id_actividad_next { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt03_atencion> CLIt03_atencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt04_atencion_dtl> CLIt04_atencion_dtl { get; set; }
    }
}
