//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt19_cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIt19_cita()
        {
            this.CLIt03_atencion = new HashSet<CLIt03_atencion>();
        }
    
        public long id_cita { get; set; }
        public string cod_cita { get; set; }
        public Nullable<System.DateTime> fec_cita { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public string hora { get; set; }
        public string duracion { get; set; }
        public string txt_obs { get; set; }
        public Nullable<int> sn_asistencia { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public long id_empleado { get; set; }
        public long id_paciente { get; set; }
    
        public virtual CLIt01_paciente CLIt01_paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt03_atencion> CLIt03_atencion { get; set; }
        public virtual PERt04_empleado PERt04_empleado { get; set; }
    }
}
