//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt01_paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIt01_paciente()
        {
            this.CLIt05_antece_alergia = new HashSet<CLIt05_antece_alergia>();
            this.CLIt03_atencion = new HashSet<CLIt03_atencion>();
            this.CLIt19_cita = new HashSet<CLIt19_cita>();
        }
    
        public long id_paciente { get; set; }
        public string cod_paciente { get; set; }
        public string nro_hist_clinica { get; set; }
        public string grupo_sanguineo { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public Nullable<int> id_ocupacion { get; set; }
        public Nullable<int> id_salud_eps { get; set; }
        public Nullable<int> id_regimen_salud { get; set; }
        public Nullable<long> id_cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt05_antece_alergia> CLIt05_antece_alergia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt03_atencion> CLIt03_atencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt19_cita> CLIt19_cita { get; set; }
        public virtual PERt02_cliente PERt02_cliente { get; set; }
        public virtual SNTt19_ocupacion SNTt19_ocupacion { get; set; }
        public virtual SNTt23_salud_eps SNTt23_salud_eps { get; set; }
        public virtual SNTt29_regimen_salud SNTt29_regimen_salud { get; set; }
    }
}
