//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt08_funciones_vitales
    {
        public long id_funciones_vitales { get; set; }
        public string cod_funciones_vitales { get; set; }
        public Nullable<System.DateTime> fec_negocio { get; set; }
        public string fec_registro { get; set; }
        public string sistoles { get; set; }
        public string diastoles { get; set; }
        public string pulsaciones { get; set; }
        public string ritmo_respiratorio { get; set; }
        public string temperatura { get; set; }
        public string altura { get; set; }
        public string peso { get; set; }
        public string imc { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public long id_atencion { get; set; }
    
        public virtual CLIt03_atencion CLIt03_atencion { get; set; }
    }
}
