//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt13_laboratorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIt13_laboratorio()
        {
            this.CLIt14_img_laboratorio = new HashSet<CLIt14_img_laboratorio>();
        }
    
        public long id_laboratorio { get; set; }
        public Nullable<System.DateTime> fec_negocio { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public string hemograma { get; set; }
        public string urinalisis { get; set; }
        public string perfil_renal { get; set; }
        public string perfil_lipidico { get; set; }
        public string perfil_hepatico { get; set; }
        public string perfil_triode { get; set; }
        public string panel_metabolico { get; set; }
        public string otros { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string txt_usuario { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public Nullable<long> id_atencion { get; set; }
    
        public virtual CLIt03_atencion CLIt03_atencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt14_img_laboratorio> CLIt14_img_laboratorio { get; set; }
    }
}
