//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt12_archivo_complementario
    {
        public long id_archivo_complelemtario { get; set; }
        public string cod_archivo_complelemtario { get; set; }
        public Nullable<long> id_estudio_complementario { get; set; }
        public string txt_path { get; set; }
        public string txt_desc { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        public virtual CLIt11_estudio_complementario CLIt11_estudio_complementario { get; set; }
    }
}
