//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt05_antece_alergia
    {
        public long id_antece_alergia { get; set; }
        public string cod_antece_alergia { get; set; }
        public Nullable<long> id_paciente { get; set; }
        public string txt_antecedentes { get; set; }
        public string txt_alergias { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        public virtual CLIt01_paciente CLIt01_paciente { get; set; }
    }
}
