//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIt11_estudio_complementario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIt11_estudio_complementario()
        {
            this.CLIt12_archivo_complementario = new HashSet<CLIt12_archivo_complementario>();
        }
    
        public long id_estudio_complementario { get; set; }
        public string cod_estudio_complementario { get; set; }
        public string txt_desc { get; set; }
        public Nullable<System.DateTime> fec_negocio { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public Nullable<long> id_atencion { get; set; }
    
        public virtual CLIt03_atencion CLIt03_atencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIt12_archivo_complementario> CLIt12_archivo_complementario { get; set; }
    }
}
