//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSHt01_caja_dtl
    {
        public long id_caja_dtl { get; set; }
        public int id_caja { get; set; }
        public long id_empleado { get; set; }
        public long id_emp_autorizador { get; set; }
        public bool sn_open { get; set; }
        public bool sn_close { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora { get; set; }
        public int id_turno { get; set; }
    
        public virtual MSTt12_caja MSTt12_caja { get; set; }
        public virtual MSTt13_turno MSTt13_turno { get; set; }
        public virtual PERt04_empleado PERt04_empleado { get; set; }
        public virtual PERt04_empleado PERt04_empleado1 { get; set; }
    }
}
