//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRLt01_parametro
    {
        public int id_parametro { get; set; }
        public string cod_parametro { get; set; }
        public string txt_desc { get; set; }
        public Nullable<decimal> dec_valor { get; set; }
        public string txt_valor { get; set; }
        public string txt_obs { get; set; }
        public int sn_edit { get; set; }
    }
}
