//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRLt04_configuracion_caja
    {
        public int id_config { get; set; }
        public int id_caja { get; set; }
        public string txt_pathlog { get; set; }
    
        public virtual MSTt12_caja MSTt12_caja { get; set; }
    }
}
