//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EagleEntities : DbContext
    {
        public EagleEntities()
            : base("name=EagleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIt01_paciente> CLIt01_paciente { get; set; }
        public virtual DbSet<CLIt02_actividad> CLIt02_actividad { get; set; }
        public virtual DbSet<CLIt03_atencion> CLIt03_atencion { get; set; }
        public virtual DbSet<CLIt04_atencion_dtl> CLIt04_atencion_dtl { get; set; }
        public virtual DbSet<CLIt05_antece_alergia> CLIt05_antece_alergia { get; set; }
        public virtual DbSet<CLIt06_tipo_especialidad> CLIt06_tipo_especialidad { get; set; }
        public virtual DbSet<CLIt07_especialidad_medica> CLIt07_especialidad_medica { get; set; }
        public virtual DbSet<CLIt08_funciones_vitales> CLIt08_funciones_vitales { get; set; }
        public virtual DbSet<CLIt09_anamnesis> CLIt09_anamnesis { get; set; }
        public virtual DbSet<CLIt10_examen_fisico> CLIt10_examen_fisico { get; set; }
        public virtual DbSet<CLIt11_estudio_complementario> CLIt11_estudio_complementario { get; set; }
        public virtual DbSet<CLIt12_archivo_complementario> CLIt12_archivo_complementario { get; set; }
        public virtual DbSet<CLIt13_laboratorio> CLIt13_laboratorio { get; set; }
        public virtual DbSet<CLIt14_img_laboratorio> CLIt14_img_laboratorio { get; set; }
        public virtual DbSet<CLIt15_diagnostico> CLIt15_diagnostico { get; set; }
        public virtual DbSet<CLIt16_cie10> CLIt16_cie10 { get; set; }
        public virtual DbSet<CLIt17_tratamiento> CLIt17_tratamiento { get; set; }
        public virtual DbSet<CLIt18_evolucion> CLIt18_evolucion { get; set; }
        public virtual DbSet<CLIt19_cita> CLIt19_cita { get; set; }
        public virtual DbSet<CSHt01_caja_dtl> CSHt01_caja_dtl { get; set; }
        public virtual DbSet<FISt01_control_numeracion> FISt01_control_numeracion { get; set; }
        public virtual DbSet<FISt02_nivel> FISt02_nivel { get; set; }
        public virtual DbSet<FISt03_tipo_numeracion> FISt03_tipo_numeracion { get; set; }
        public virtual DbSet<GRLt01_parametro> GRLt01_parametro { get; set; }
        public virtual DbSet<GRLt02_estado> GRLt02_estado { get; set; }
        public virtual DbSet<GRLt03_horario> GRLt03_horario { get; set; }
        public virtual DbSet<GRLt04_configuracion_caja> GRLt04_configuracion_caja { get; set; }
        public virtual DbSet<MSTt01_medio_pago> MSTt01_medio_pago { get; set; }
        public virtual DbSet<MSTt02_descuento> MSTt02_descuento { get; set; }
        public virtual DbSet<MSTt03_tipo_orden> MSTt03_tipo_orden { get; set; }
        public virtual DbSet<MSTt04_canal_vta> MSTt04_canal_vta { get; set; }
        public virtual DbSet<MSTt05_razon> MSTt05_razon { get; set; }
        public virtual DbSet<MSTt06_impuesto> MSTt06_impuesto { get; set; }
        public virtual DbSet<MSTt07_estado_civil> MSTt07_estado_civil { get; set; }
        public virtual DbSet<MSTt08_location> MSTt08_location { get; set; }
        public virtual DbSet<MSTt09_tipo_location> MSTt09_tipo_location { get; set; }
        public virtual DbSet<MSTt10_impresora> MSTt10_impresora { get; set; }
        public virtual DbSet<MSTt11_tipo_impresora> MSTt11_tipo_impresora { get; set; }
        public virtual DbSet<MSTt12_caja> MSTt12_caja { get; set; }
        public virtual DbSet<MSTt13_turno> MSTt13_turno { get; set; }
        public virtual DbSet<MSTt14_mesa> MSTt14_mesa { get; set; }
        public virtual DbSet<MSTt15_estado_mesa> MSTt15_estado_mesa { get; set; }
        public virtual DbSet<PERt01_usuario> PERt01_usuario { get; set; }
        public virtual DbSet<PERt02_cliente> PERt02_cliente { get; set; }
        public virtual DbSet<PERt03_proveedor> PERt03_proveedor { get; set; }
        public virtual DbSet<PERt04_empleado> PERt04_empleado { get; set; }
        public virtual DbSet<PERt05_categoria_emp> PERt05_categoria_emp { get; set; }
        public virtual DbSet<PERt06_clase_emp> PERt06_clase_emp { get; set; }
        public virtual DbSet<PROt01_marca> PROt01_marca { get; set; }
        public virtual DbSet<PROt02_modelo> PROt02_modelo { get; set; }
        public virtual DbSet<PROt03_familia> PROt03_familia { get; set; }
        public virtual DbSet<PROt04_subfamilia> PROt04_subfamilia { get; set; }
        public virtual DbSet<PROt05_grupo_prod> PROt05_grupo_prod { get; set; }
        public virtual DbSet<PROt06_clase_prod> PROt06_clase_prod { get; set; }
        public virtual DbSet<PROt07_tipo_prod> PROt07_tipo_prod { get; set; }
        public virtual DbSet<PROt08_precio_prod> PROt08_precio_prod { get; set; }
        public virtual DbSet<PROt09_producto> PROt09_producto { get; set; }
        public virtual DbSet<PROt10_receta> PROt10_receta { get; set; }
        public virtual DbSet<PROt11_receta_dtl> PROt11_receta_dtl { get; set; }
        public virtual DbSet<PROt12_receta_grupo> PROt12_receta_grupo { get; set; }
        public virtual DbSet<PROt13_combo> PROt13_combo { get; set; }
        public virtual DbSet<PROt14_combo_fixed_dtl> PROt14_combo_fixed_dtl { get; set; }
        public virtual DbSet<PROt15_combo_variable> PROt15_combo_variable { get; set; }
        public virtual DbSet<PROt16_combo_variable_dtl> PROt16_combo_variable_dtl { get; set; }
        public virtual DbSet<PROt17_combo_grupo> PROt17_combo_grupo { get; set; }
        public virtual DbSet<RPTt01_reporte> RPTt01_reporte { get; set; }
        public virtual DbSet<RPTt02_categoria_reporte> RPTt02_categoria_reporte { get; set; }
        public virtual DbSet<SNTt01_tipo_medio_pago> SNTt01_tipo_medio_pago { get; set; }
        public virtual DbSet<SNTt02_tipo_doc_identidad> SNTt02_tipo_doc_identidad { get; set; }
        public virtual DbSet<SNTt03_entidad_financiera> SNTt03_entidad_financiera { get; set; }
        public virtual DbSet<SNTt04_tipo_moneda> SNTt04_tipo_moneda { get; set; }
        public virtual DbSet<SNTt05_tipo_existencia> SNTt05_tipo_existencia { get; set; }
        public virtual DbSet<SNTt06_unidad_medida> SNTt06_unidad_medida { get; set; }
        public virtual DbSet<SNTt07_tipo_intangible> SNTt07_tipo_intangible { get; set; }
        public virtual DbSet<SNTt08_codigo_libro> SNTt08_codigo_libro { get; set; }
        public virtual DbSet<SNTt09_cta_contable> SNTt09_cta_contable { get; set; }
        public virtual DbSet<SNTt10_tipo_comprobante> SNTt10_tipo_comprobante { get; set; }
        public virtual DbSet<SNTt11_aduana> SNTt11_aduana { get; set; }
        public virtual DbSet<SNTt12_tipo_operacion> SNTt12_tipo_operacion { get; set; }
        public virtual DbSet<SNTt13_tipo_actividad> SNTt13_tipo_actividad { get; set; }
        public virtual DbSet<SNTt14_nacionalidad> SNTt14_nacionalidad { get; set; }
        public virtual DbSet<SNTt15_via> SNTt15_via { get; set; }
        public virtual DbSet<SNTt16_zona> SNTt16_zona { get; set; }
        public virtual DbSet<SNTt17_tipo_trabajador> SNTt17_tipo_trabajador { get; set; }
        public virtual DbSet<SNTt18_situacion_educativa> SNTt18_situacion_educativa { get; set; }
        public virtual DbSet<SNTt19_ocupacion> SNTt19_ocupacion { get; set; }
        public virtual DbSet<SNTt20_regimen_pensionario> SNTt20_regimen_pensionario { get; set; }
        public virtual DbSet<SNTt21_condicion_laboral> SNTt21_condicion_laboral { get; set; }
        public virtual DbSet<SNTt22_periodo_remuneracion> SNTt22_periodo_remuneracion { get; set; }
        public virtual DbSet<SNTt23_salud_eps> SNTt23_salud_eps { get; set; }
        public virtual DbSet<SNTt24_situacion> SNTt24_situacion { get; set; }
        public virtual DbSet<SNTt25_motivo_baja> SNTt25_motivo_baja { get; set; }
        public virtual DbSet<SNTt26_modalidad_formativa> SNTt26_modalidad_formativa { get; set; }
        public virtual DbSet<SNTt27_vinculo_familiar> SNTt27_vinculo_familiar { get; set; }
        public virtual DbSet<SNTt28_suspencion_laboral> SNTt28_suspencion_laboral { get; set; }
        public virtual DbSet<SNTt29_regimen_salud> SNTt29_regimen_salud { get; set; }
        public virtual DbSet<SNTt30_regimen_laboral> SNTt30_regimen_laboral { get; set; }
        public virtual DbSet<SNTt31_departamento> SNTt31_departamento { get; set; }
        public virtual DbSet<SNTt32_provincia> SNTt32_provincia { get; set; }
        public virtual DbSet<SNTt33_distrito> SNTt33_distrito { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TNSt01_comp_recibido> TNSt01_comp_recibido { get; set; }
        public virtual DbSet<TNSt02_comp_recibido_dtl> TNSt02_comp_recibido_dtl { get; set; }
        public virtual DbSet<TNSt03_comp_recibido_estado> TNSt03_comp_recibido_estado { get; set; }
        public virtual DbSet<TNSt04_comp_emitido> TNSt04_comp_emitido { get; set; }
        public virtual DbSet<TNSt05_comp_emitido_dtl> TNSt05_comp_emitido_dtl { get; set; }
        public virtual DbSet<TNSt06_comp_emitido_estado> TNSt06_comp_emitido_estado { get; set; }
        public virtual DbSet<TNSt07_medio_pago_dtl> TNSt07_medio_pago_dtl { get; set; }
        public virtual DbSet<TNSt08_descuento_dtl> TNSt08_descuento_dtl { get; set; }
        public virtual DbSet<TOTt01_total_diario_vta> TOTt01_total_diario_vta { get; set; }
    }
}
