//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTt02_descuento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTt02_descuento()
        {
            this.TNSt08_descuento_dtl = new HashSet<TNSt08_descuento_dtl>();
        }
    
        public int id_descuento { get; set; }
        public string cod_descuento { get; set; }
        public string txt_desc { get; set; }
        public string tipo_descuento { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> monto_min { get; set; }
        public Nullable<decimal> monto_max { get; set; }
        public Nullable<int> sn_descuen_periodo { get; set; }
        public Nullable<int> sn_descuen_dia { get; set; }
        public Nullable<System.DateTime> p1_fecha_ini { get; set; }
        public Nullable<System.DateTime> p1_fecha_fin { get; set; }
        public Nullable<System.TimeSpan> p1_hora_ini { get; set; }
        public Nullable<System.TimeSpan> p1_hora_fin { get; set; }
        public Nullable<System.DateTime> p2_fecha_ini { get; set; }
        public Nullable<System.DateTime> p2_fecha_fin { get; set; }
        public Nullable<System.TimeSpan> p2_hora_ini { get; set; }
        public Nullable<System.TimeSpan> p2_hora_fin { get; set; }
        public Nullable<System.DateTime> p3_fecha_ini { get; set; }
        public Nullable<System.DateTime> p3_fecha_fin { get; set; }
        public Nullable<System.TimeSpan> p3_hora_ini { get; set; }
        public Nullable<System.TimeSpan> p3_hora_fin { get; set; }
        public Nullable<System.DateTime> p4_fecha_ini { get; set; }
        public Nullable<System.DateTime> p4_fecha_fin { get; set; }
        public Nullable<System.TimeSpan> p4_hora_ini { get; set; }
        public Nullable<System.TimeSpan> p4_hora_fin { get; set; }
        public Nullable<System.DateTime> p5_fecha_ini { get; set; }
        public Nullable<System.DateTime> p5_fecha_fin { get; set; }
        public Nullable<System.TimeSpan> p5_hora_ini { get; set; }
        public Nullable<System.TimeSpan> p5_hora_fin { get; set; }
        public Nullable<System.DateTime> p6_fecha_ini { get; set; }
        public Nullable<System.DateTime> p6_fecha_fin { get; set; }
        public Nullable<System.TimeSpan> p6_hora_ini { get; set; }
        public Nullable<System.TimeSpan> p6_hora_fin { get; set; }
        public Nullable<System.DateTime> p7_fecha_ini { get; set; }
        public Nullable<System.DateTime> p7_fecha_fin { get; set; }
        public Nullable<System.TimeSpan> p7_hora_ini { get; set; }
        public Nullable<System.TimeSpan> p7_hora_fin { get; set; }
        public Nullable<int> sn_domingo { get; set; }
        public Nullable<int> sn_lunes { get; set; }
        public Nullable<int> sn_martes { get; set; }
        public Nullable<int> sn_miercoles { get; set; }
        public Nullable<int> sn_jueves { get; set; }
        public Nullable<int> sn_viernes { get; set; }
        public Nullable<int> sn_sabado { get; set; }
        public Nullable<System.TimeSpan> dom_hora_ini { get; set; }
        public Nullable<System.TimeSpan> dom_hora_fin { get; set; }
        public Nullable<System.TimeSpan> lun_hora_ini { get; set; }
        public Nullable<System.TimeSpan> lun_hora_fin { get; set; }
        public Nullable<System.TimeSpan> mar_hora_ini { get; set; }
        public Nullable<System.TimeSpan> mar_hora_fin { get; set; }
        public Nullable<System.TimeSpan> mie_hora_ini { get; set; }
        public Nullable<System.TimeSpan> mie_hora_fin { get; set; }
        public Nullable<System.TimeSpan> jue_hora_ini { get; set; }
        public Nullable<System.TimeSpan> jue_hora_fin { get; set; }
        public Nullable<System.TimeSpan> vie_hora_ini { get; set; }
        public Nullable<System.TimeSpan> vie_hora_fin { get; set; }
        public Nullable<System.TimeSpan> sab_hora_ini { get; set; }
        public Nullable<System.TimeSpan> sab_hora_fin { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt08_descuento_dtl> TNSt08_descuento_dtl { get; set; }
    }
}
