//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTt15_estado_mesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTt15_estado_mesa()
        {
            this.MSTt14_mesa = new HashSet<MSTt14_mesa>();
        }
    
        public int id_estado_mesa { get; set; }
        public string cod_estado_mesa { get; set; }
        public string txt_desc { get; set; }
        public string txt_color_hex { get; set; }
        public int id_estado { get; set; }
        public string txt_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTt14_mesa> MSTt14_mesa { get; set; }
    }
}
