//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTt11_tipo_impresora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTt11_tipo_impresora()
        {
            this.MSTt10_impresora = new HashSet<MSTt10_impresora>();
        }
    
        public int id_tipo_impresora { get; set; }
        public string cod_tipo_impresora { get; set; }
        public string txt_desc { get; set; }
        public string txt_info01 { get; set; }
        public int id_estado { get; set; }
        public string txt_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTt10_impresora> MSTt10_impresora { get; set; }
    }
}
