//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTt14_mesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTt14_mesa()
        {
            this.TNSt04_comp_emitido = new HashSet<TNSt04_comp_emitido>();
        }
    
        public int id_mesa { get; set; }
        public string cod_mesa { get; set; }
        public string txt_num { get; set; }
        public int capacidad { get; set; }
        public Nullable<int> id_can_vta { get; set; }
        public int id_estado_mesa { get; set; }
    
        public virtual MSTt04_canal_vta MSTt04_canal_vta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt04_comp_emitido> TNSt04_comp_emitido { get; set; }
        public virtual MSTt15_estado_mesa MSTt15_estado_mesa { get; set; }
    }
}
