//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTt01_medio_pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTt01_medio_pago()
        {
            this.TNSt07_medio_pago_dtl = new HashSet<TNSt07_medio_pago_dtl>();
        }
    
        public int id_medio_pago { get; set; }
        public string cod_medio_pago { get; set; }
        public string txt_desc { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public Nullable<int> id_tipo_medio_pago { get; set; }
    
        public virtual SNTt01_tipo_medio_pago SNTt01_tipo_medio_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt07_medio_pago_dtl> TNSt07_medio_pago_dtl { get; set; }
    }
}
