//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTt08_location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTt08_location()
        {
            this.TNSt04_comp_emitido = new HashSet<TNSt04_comp_emitido>();
        }
    
        public int id_location { get; set; }
        public string cod_location { get; set; }
        public string txt_desc { get; set; }
        public Nullable<System.DateTime> fecha_negocio { get; set; }
        public string txt_direccion1 { get; set; }
        public string txt_direccion2 { get; set; }
        public string txt_abrev1 { get; set; }
        public string txt_abrev2 { get; set; }
        public string nro_ruc { get; set; }
        public string fono1 { get; set; }
        public string fono2 { get; set; }
        public string txt_datos1 { get; set; }
        public string txt_datos2 { get; set; }
        public string txt_datos3 { get; set; }
        public string txt_datos4 { get; set; }
        public Nullable<int> sn_almacen { get; set; }
        public Nullable<int> sn_location_current { get; set; }
        public int id_tipo_location { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt04_comp_emitido> TNSt04_comp_emitido { get; set; }
        public virtual MSTt09_tipo_location MSTt09_tipo_location { get; set; }
    }
}
