//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTt10_impresora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MSTt10_impresora()
        {
            this.MSTt12_caja = new HashSet<MSTt12_caja>();
            this.MSTt12_caja1 = new HashSet<MSTt12_caja>();
            this.MSTt12_caja2 = new HashSet<MSTt12_caja>();
            this.MSTt12_caja3 = new HashSet<MSTt12_caja>();
            this.MSTt12_caja4 = new HashSet<MSTt12_caja>();
            this.MSTt12_caja5 = new HashSet<MSTt12_caja>();
        }
    
        public int id_impresora { get; set; }
        public string cod_impresora { get; set; }
        public string txt_desc { get; set; }
        public string txt_ip { get; set; }
        public int id_tipo_impresora { get; set; }
        public string txt_marca { get; set; }
        public string txt_modelo { get; set; }
        public string txt_info01 { get; set; }
        public int id_estado { get; set; }
        public string txt_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTt12_caja> MSTt12_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTt12_caja> MSTt12_caja1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTt12_caja> MSTt12_caja2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTt12_caja> MSTt12_caja3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTt12_caja> MSTt12_caja4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSTt12_caja> MSTt12_caja5 { get; set; }
        public virtual MSTt11_tipo_impresora MSTt11_tipo_impresora { get; set; }
    }
}
