//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERt03_proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERt03_proveedor()
        {
            this.TNSt01_comp_recibido = new HashSet<TNSt01_comp_recibido>();
        }
    
        public long id_proveedor { get; set; }
        public string cod_proveedor { get; set; }
        public string cod_tipo_per { get; set; }
        public string nro_doc { get; set; }
        public string nro_ruc { get; set; }
        public string sexo { get; set; }
        public string txt_ape_pat { get; set; }
        public string txt_ape_mat { get; set; }
        public string txt_pri_nom { get; set; }
        public string txt_seg_nom { get; set; }
        public Nullable<System.DateTime> fec_nac { get; set; }
        public string txt_rzn_social { get; set; }
        public string txt_nom_comercial { get; set; }
        public string nom_via { get; set; }
        public string nro_via { get; set; }
        public string nom_zona { get; set; }
        public string txt_direccion1 { get; set; }
        public string txt_direccion2 { get; set; }
        public string txt_referencia { get; set; }
        public string txt_email1 { get; set; }
        public string txt_email2 { get; set; }
        public string txt_web { get; set; }
        public string telef_fijo1 { get; set; }
        public string telef_fijo2 { get; set; }
        public string telef_fijo3 { get; set; }
        public string celular1 { get; set; }
        public string celular2 { get; set; }
        public string celular3 { get; set; }
        public string url_img { get; set; }
        public string info01 { get; set; }
        public string info02 { get; set; }
        public string info03 { get; set; }
        public string info04 { get; set; }
        public string info05 { get; set; }
        public string info06 { get; set; }
        public string info07 { get; set; }
        public string info08 { get; set; }
        public string info09 { get; set; }
        public string info10 { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public Nullable<int> id_dist { get; set; }
        public Nullable<int> id_via { get; set; }
        public Nullable<int> id_zona { get; set; }
        public Nullable<int> id_tipo_doc_identidad { get; set; }
        public Nullable<int> id_nacionalidad { get; set; }
        public Nullable<int> id_estado_civil { get; set; }
    
        public virtual MSTt07_estado_civil MSTt07_estado_civil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt01_comp_recibido> TNSt01_comp_recibido { get; set; }
        public virtual SNTt02_tipo_doc_identidad SNTt02_tipo_doc_identidad { get; set; }
        public virtual SNTt14_nacionalidad SNTt14_nacionalidad { get; set; }
        public virtual SNTt15_via SNTt15_via { get; set; }
        public virtual SNTt16_zona SNTt16_zona { get; set; }
        public virtual SNTt33_distrito SNTt33_distrito { get; set; }
    }
}
