//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROt08_precio_prod
    {
        public long id_precio_prod { get; set; }
        public Nullable<long> id_producto { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_1 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_2 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_3 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_4 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_5 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_6 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_7 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_8 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_9 { get; set; }
        public Nullable<decimal> mto_pu_sin_igv_10 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_1 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_2 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_3 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_4 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_5 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_6 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_7 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_8 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_9 { get; set; }
        public Nullable<decimal> mto_pu_con_igv_10 { get; set; }
        public Nullable<decimal> mto_costo_1 { get; set; }
        public Nullable<decimal> mto_costo_2 { get; set; }
        public Nullable<decimal> mto_costo_3 { get; set; }
        public Nullable<decimal> mto_costo_4 { get; set; }
        public Nullable<decimal> mto_costo_5 { get; set; }
        public Nullable<decimal> mto_costo_6 { get; set; }
        public Nullable<decimal> mto_costo_7 { get; set; }
        public Nullable<decimal> mto_costo_8 { get; set; }
        public Nullable<decimal> mto_costo_9 { get; set; }
        public Nullable<decimal> mto_costo_10 { get; set; }
        public Nullable<System.DateTime> fec_efectivo_desde { get; set; }
        public Nullable<System.DateTime> fec_efectivo_hasta { get; set; }
        public string txt_obsv { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        public virtual PROt09_producto PROt09_producto { get; set; }
    }
}
