//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROt15_combo_variable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROt15_combo_variable()
        {
            this.PROt14_combo_fixed_dtl = new HashSet<PROt14_combo_fixed_dtl>();
            this.PROt16_combo_variable_dtl = new HashSet<PROt16_combo_variable_dtl>();
        }
    
        public int id_combo_variable { get; set; }
        public string cod_combo_variable { get; set; }
        public string txt_desc { get; set; }
        public decimal mto_pvpu_sin_tax { get; set; }
        public decimal mto_pvpu_con_tax { get; set; }
        public int id_estado { get; set; }
        public string txt_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROt14_combo_fixed_dtl> PROt14_combo_fixed_dtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROt16_combo_variable_dtl> PROt16_combo_variable_dtl { get; set; }
    }
}
