//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROt11_receta_dtl
    {
        public long id_receta_dtl { get; set; }
        public Nullable<long> id_producto { get; set; }
        public string txt_producto { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public int id_um { get; set; }
        public long id_receta { get; set; }
    
        public virtual PROt09_producto PROt09_producto { get; set; }
        public virtual PROt10_receta PROt10_receta { get; set; }
        public virtual SNTt06_unidad_medida SNTt06_unidad_medida { get; set; }
    }
}
