//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROt13_combo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROt13_combo()
        {
            this.PROt09_producto = new HashSet<PROt09_producto>();
            this.PROt14_combo_fixed_dtl = new HashSet<PROt14_combo_fixed_dtl>();
        }
    
        public long id_combo { get; set; }
        public string cod_combo { get; set; }
        public string txt_desc { get; set; }
        public decimal mto_pvpu_sin_tax { get; set; }
        public decimal mto_pvpu_con_tax { get; set; }
        public int id_estado { get; set; }
        public string txt_estado { get; set; }
        public int id_combo_grupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROt09_producto> PROt09_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROt14_combo_fixed_dtl> PROt14_combo_fixed_dtl { get; set; }
        public virtual PROt17_combo_grupo PROt17_combo_grupo { get; set; }
    }
}
