//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNTt32_provincia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SNTt32_provincia()
        {
            this.SNTt33_distrito = new HashSet<SNTt33_distrito>();
        }
    
        public int id_prov { get; set; }
        public string cod_prov { get; set; }
        public string cod_prov_ple { get; set; }
        public string txt_desc { get; set; }
        public int id_dpto { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        public virtual SNTt31_departamento SNTt31_departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SNTt33_distrito> SNTt33_distrito { get; set; }
    }
}
