//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNTt06_unidad_medida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SNTt06_unidad_medida()
        {
            this.PROt09_producto = new HashSet<PROt09_producto>();
            this.PROt11_receta_dtl = new HashSet<PROt11_receta_dtl>();
            this.TNSt02_comp_recibido_dtl = new HashSet<TNSt02_comp_recibido_dtl>();
            this.TNSt05_comp_emitido_dtl = new HashSet<TNSt05_comp_emitido_dtl>();
        }
    
        public int id_um { get; set; }
        public string cod_um { get; set; }
        public string cod_um_ple { get; set; }
        public string txt_abrv { get; set; }
        public string txt_desc { get; set; }
        public string txt_unid_base { get; set; }
        public Nullable<int> id_um_base { get; set; }
        public string txt_operacion { get; set; }
        public Nullable<decimal> dec_factor { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROt09_producto> PROt09_producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROt11_receta_dtl> PROt11_receta_dtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt02_comp_recibido_dtl> TNSt02_comp_recibido_dtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt05_comp_emitido_dtl> TNSt05_comp_emitido_dtl { get; set; }
    }
}
