//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt08_descuento_dtl
    {
        public long id_descuento_dtl { get; set; }
        public Nullable<long> id_comp_emitido { get; set; }
        public int id_descuento { get; set; }
        public Nullable<decimal> porcentaje { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<int> id_razon { get; set; }
        public string txt_observ { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        public virtual MSTt02_descuento MSTt02_descuento { get; set; }
        public virtual MSTt05_razon MSTt05_razon { get; set; }
        public virtual TNSt04_comp_emitido TNSt04_comp_emitido { get; set; }
    }
}
