//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt02_comp_recibido_dtl
    {
        public long id_comp_recibido_dtl { get; set; }
        public Nullable<long> id_comp_recibido { get; set; }
        public long id_producto { get; set; }
        public string txt_producto { get; set; }
        public int id_um { get; set; }
        public decimal qt_comp { get; set; }
        public Nullable<decimal> punit_sin_igv { get; set; }
        public Nullable<decimal> punit_con_igv { get; set; }
        public Nullable<decimal> por_dscto { get; set; }
        public Nullable<decimal> punit_dscto_sin_igv { get; set; }
        public Nullable<decimal> punit_dscto_con_igv { get; set; }
        public Nullable<decimal> mto_comp_sin_igv { get; set; }
        public Nullable<decimal> mto_comp_con_igv { get; set; }
    
        public virtual PROt09_producto PROt09_producto { get; set; }
        public virtual SNTt06_unidad_medida SNTt06_unidad_medida { get; set; }
        public virtual TNSt01_comp_recibido TNSt01_comp_recibido { get; set; }
    }
}
