//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt01_comp_recibido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TNSt01_comp_recibido()
        {
            this.TNSt02_comp_recibido_dtl = new HashSet<TNSt02_comp_recibido_dtl>();
            this.TNSt03_comp_recibido_estado = new HashSet<TNSt03_comp_recibido_estado>();
        }
    
        public long id_comp_recibido { get; set; }
        public string nro_comp_recibido { get; set; }
        public int id_tipo_comp { get; set; }
        public string txt_serie { get; set; }
        public string txt_numero { get; set; }
        public System.DateTime fec_reg_recibido { get; set; }
        public System.DateTime fec_emi { get; set; }
        public Nullable<System.DateTime> fec_vcto { get; set; }
        public Nullable<System.DateTime> fec_canc { get; set; }
        public int id_tipo_moneda { get; set; }
        public Nullable<int> id_tipo_orden { get; set; }
        public decimal por_impto { get; set; }
        public string txt_observ { get; set; }
        public decimal mto_tc_vta { get; set; }
        public decimal mto_neto { get; set; }
        public decimal mto_exonerado { get; set; }
        public decimal mto_no_afecto { get; set; }
        public decimal mto_dscto_tot { get; set; }
        public decimal mto_cms_tot { get; set; }
        public decimal mto_flete_tot { get; set; }
        public decimal mto_sub_tot { get; set; }
        public decimal mto_impto_tot { get; set; }
        public decimal mto_servicio { get; set; }
        public decimal mto_tot_comp { get; set; }
        public string ref_tipo_comprobante { get; set; }
        public Nullable<System.DateTime> ref_fecha { get; set; }
        public string ref_serie { get; set; }
        public string ref_numero { get; set; }
        public Nullable<int> sn_credito { get; set; }
        public Nullable<int> sn_cancelada { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public string txt_usuario { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public Nullable<long> id_proveedor { get; set; }
        public int id_impuesto { get; set; }
    
        public virtual MSTt03_tipo_orden MSTt03_tipo_orden { get; set; }
        public virtual MSTt06_impuesto MSTt06_impuesto { get; set; }
        public virtual PERt01_usuario PERt01_usuario { get; set; }
        public virtual PERt03_proveedor PERt03_proveedor { get; set; }
        public virtual SNTt04_tipo_moneda SNTt04_tipo_moneda { get; set; }
        public virtual SNTt10_tipo_comprobante SNTt10_tipo_comprobante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt02_comp_recibido_dtl> TNSt02_comp_recibido_dtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TNSt03_comp_recibido_estado> TNSt03_comp_recibido_estado { get; set; }
    }
}
