//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt07_medio_pago_dtl
    {
        public long id_medio_pago_dtl { get; set; }
        public Nullable<long> id_comp_emitido { get; set; }
        public Nullable<int> id_medio_pago { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<decimal> mto_tipo_cambio { get; set; }
        public string txt_observ { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    
        public virtual MSTt01_medio_pago MSTt01_medio_pago { get; set; }
        public virtual TNSt04_comp_emitido TNSt04_comp_emitido { get; set; }
    }
}
