//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt06_comp_emitido_estado
    {
        public long id_comp_emitido_estado { get; set; }
        public Nullable<long> id_comp_emitido { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public string txt_usuario { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual TNSt04_comp_emitido TNSt04_comp_emitido { get; set; }
    }
}
