//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNSt03_comp_recibido_estado
    {
        public long id_comp_recibido_estado { get; set; }
        public Nullable<long> id_comp_recibido { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
        public string txt_usuario { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        public virtual TNSt01_comp_recibido TNSt01_comp_recibido { get; set; }
    }
}
