//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOTt01_total_diario_vta
    {
        public long id_total_diario_vta { get; set; }
        public Nullable<int> id_location { get; set; }
        public System.DateTime fec_registro { get; set; }
        public System.DateTime fec_negocio { get; set; }
        public Nullable<int> cant_ordenes { get; set; }
        public Nullable<decimal> mto_ordenes { get; set; }
        public Nullable<int> cant_boletas { get; set; }
        public Nullable<decimal> mto_boletas { get; set; }
        public Nullable<int> cant_facturas { get; set; }
        public Nullable<decimal> mto_facturas { get; set; }
        public Nullable<int> cant_not_cred { get; set; }
        public Nullable<decimal> mto_not_cred { get; set; }
        public Nullable<int> cant_comprobantes { get; set; }
        public Nullable<decimal> mto_comprobantes { get; set; }
        public Nullable<decimal> mto_forma_pago01 { get; set; }
        public Nullable<decimal> mto_forma_pago02 { get; set; }
        public Nullable<decimal> mto_forma_pago03 { get; set; }
        public Nullable<decimal> mto_forma_pago04 { get; set; }
        public Nullable<decimal> mto_forma_pago05 { get; set; }
        public Nullable<decimal> mto_forma_pago06 { get; set; }
        public Nullable<decimal> mto_forma_pago07 { get; set; }
        public Nullable<decimal> mto_forma_pago08 { get; set; }
        public Nullable<decimal> mto_forma_pago09 { get; set; }
        public Nullable<decimal> mto_forma_pago10 { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string txt_usuario { get; set; }
        public Nullable<int> id_estado { get; set; }
        public string txt_estado { get; set; }
    }
}
